from jaxweights._bundle import ParamBundle, ParamSpec, RequestSpec
from jaxweights._core import transform, param
from jaxweights._context import scope
from jaxweights._initializers import (
    zeros,
    zeroes,
    ones,
    constant,
    normal,
    norm,
    truncated_normal,
    uniform,
    lecun_normal,
    lecun_uniform,
    xavier_normal,
    glorot_normal,
    xavier_uniform,
    glorot_uniform,
    he_normal,
    kaiming_normal,
    he_uniform,
    kaiming_uniform,
    orthogonal,
    identity,
    xavier,
    he,
)
from jaxweights._errors import (
    JaxWeightsError,
    ContextError,
    DuplicateParameterError,
    ReservedNameError,
    ShapeMismatchError,
    DTypeMismatchError,
    MissingParameterError,
    TraceMismatchError,
    SpecError,
)

__version__ = "0.1.0"

__all__ = [
    "ParamBundle",
    "ParamSpec",
    "RequestSpec",
    "transform",
    "param",
    "scope",
    "zeros",
    "zeroes",
    "ones",
    "constant",
    "normal",
    "norm",
    "truncated_normal",
    "uniform",
    "lecun_normal",
    "lecun_uniform",
    "xavier_normal",
    "glorot_normal",
    "xavier_uniform",
    "glorot_uniform",
    "he_normal",
    "kaiming_normal",
    "he_uniform",
    "kaiming_uniform",
    "orthogonal",
    "identity",
    "xavier",
    "he",
    "JaxWeightsError",
    "ContextError",
    "DuplicateParameterError",
    "ReservedNameError",
    "ShapeMismatchError",
    "DTypeMismatchError",
    "MissingParameterError",
    "TraceMismatchError",
    "SpecError",
]
